### ISSUE TITLE
FATA[0000] json: cannot unmarshal object into Go struct field .hits.total of type int64 

### ISSUE THREAD

**Issue by s-marios** [miku/esdump#1]
Hi, 
Tried to get data out of an index and got the error in the title. Running ELK 7.9.1.The actual command used was the following:
`esdump -verbose -s http://localhost:9200 -i an_index_that_exists`
Cheers,

**Comment by s-marios** [comment]
Digging a bit deeper with wireshark, the `total` is now an object with two members, `value` and `relation`. This is also confirmed here : https://www.elastic.co/guide/en/elasticsearch/reference/7.9/search-search.html under the response body -> hits -> total section.

Ah, isn't it fun when APIs change?

**Comment by miku** [comment]
Thanks for the report and the details! A more automated, isolated test suite for various es versions is unfortunately an outstanding issue.

**Comment by miku** [comment]
For the record, [v0.1.9](https://github.com/miku/esdump/releases/tag/v0.1.9) fixes the ES6/7 API change and should work seamlessly with both elasticsearch 6 and 7+.
