### ISSUE TITLE
FATA[0000] invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by fchiao** [miku/esdump#2]
As title, when using the command: 
esdump -s http://192.168.5.16 -i zeek_anon_* -scroll "1m" -size 100 -verbose
it always says that there are invalid character.
Googled and found similar issue here: https://github.com/olivere/elastic/issues/1252
but unable to solve the issue.

**Comment by miku** [comment]
Thanks for the bug report. 

I released a esdump 0.1.10, which logs the last response body - so it may give a clue of what's the problem.

[https://github.com/miku/esdump/releases/tag/v0.1.10](https://github.com/miku/esdump/releases/tag/v0.1.10)

**Comment by fchiao** [comment]
Thank you, that helped a lot in debugging.
